import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";

function readRepoFile(path: string) {
  return readFileSync(new URL(`../${path}`, import.meta.url), "utf8");
}

test("jobs filters support scoped search, removable chips, compact filters, and salary range", () => {
  const querySource = readRepoFile("src/lib/queries/jobs.ts");
  const filterContractSource = readRepoFile("src/lib/job-filter-contract.ts");
  const metadataSource = readRepoFile("src/lib/job-metadata.ts");
  const pageSource = readRepoFile("src/app/jobs/page.tsx");
  const resultCountSource = readRepoFile("src/lib/jobs/result-count.ts");
  const activeChipsSource = readRepoFile("src/components/jobs/jobs-active-filter-chips.tsx");
  const filterFieldSource = readRepoFile("src/components/jobs/jobs-filter-field.tsx");
  const searchFormSource = readRepoFile("src/components/jobs/jobs-search-form.tsx");
  const pendingBoundarySource = readRepoFile("src/components/jobs/jobs-navigation-pending-boundary.tsx");
  const loadingPopupSource = readRepoFile("src/components/jobs/jobs-loading-popup.tsx");
  const appShellSource = readRepoFile("src/components/layout/app-shell.tsx");
  const jobsLoadingSource = readRepoFile("src/app/jobs/loading.tsx");
  const naturalLanguageSearchSource = readRepoFile("src/components/jobs/natural-language-job-search.tsx");
  const searchParamMemorySource = readRepoFile("src/components/navigation/search-param-memory.tsx");
  const savedFiltersControlSource = readRepoFile("src/components/jobs/jobs-saved-filters-control.tsx");
  const paginationSource = readRepoFile("src/components/navigation/pagination-controls.tsx");

  assert.match(querySource, /location\?: string/);
  assert.match(querySource, /searchScope\?: JobSearchScope/);
  assert.match(querySource, /titleSearch\?: string/);
  assert.match(querySource, /companySearch\?: string/);
  assert.match(querySource, /locationSearch\?: string/);
  assert.match(querySource, /source\?: string/);
  assert.match(querySource, /employmentType\?: string/);
  assert.match(querySource, /careerStage\?: string/);
  assert.match(querySource, /roleCategory\?: string/);
  assert.match(querySource, /includeUnknownSalary\?: boolean/);
  assert.match(querySource, /hideApplied\?: boolean/);
  assert.match(querySource, /posted\?: string/);
  assert.match(querySource, /salaryMax\?: number/);
  assert.match(querySource, /expandLocationSearchTerm/);
  assert.match(querySource, /appendFeedIndexLocationSearchWhere\(where, filters\.location\)/);
  assert.match(querySource, /appendScopedTextSearchWhere\(where, "title", filters\.titleSearch\)/);
  assert.match(querySource, /appendScopedTextSearchWhere\(where, "company", filters\.companySearch\)/);
  assert.match(querySource, /appendLocationSearchWhere\(where, filters\.locationSearch\)/);
  assert.match(querySource, /return clauses\.length === 1 \? clauses\[0\] : \{ OR: clauses \}/);
  assert.match(querySource, /sourceMappings:\s*\{\s*some:\s*\{[\s\S]*sourceName:\s*\{\s*contains: filters\.source/);
  assert.match(querySource, /employmentTypeGroup:\s*employmentTypeGroups\.length > 0/);
  assert.match(querySource, /employmentTypeConfidence:\s*\{\s*gte: METADATA_FIELD_FILTER_CONFIDENCE_THRESHOLD/);
  assert.match(querySource, /experienceLevelGroup:\s*knownGroups\.length > 0/);
  assert.match(querySource, /normalizedCareerStageConfidence:\s*\{\s*gte: CAREER_STAGE_FILTER_CONFIDENCE_THRESHOLD/);
  assert.match(querySource, /normalizedIndustries:\s*\{\s*hasSome: industries \}/);
  assert.match(querySource, /normalizedIndustryConfidence:\s*\{\s*gte: INDUSTRY_FILTER_CONFIDENCE_THRESHOLD/);
  assert.match(querySource, /normalizedRoleCategory/);
  assert.match(querySource, /normalizedRoleCategoryConfidence:\s*\{\s*gte: ROLE_CATEGORY_FILTER_CONFIDENCE_THRESHOLD/);
  assert.match(querySource, /classificationStatus:\s*\{\s*in:\s*\[\.\.\.FILTERABLE_CLASSIFICATION_STATUSES\]/);
  assert.match(querySource, /assertJobFilterContract/);
  assert.match(filterContractSource, /getJobFilterContractViolations/);
  assert.match(filterContractSource, /role_category_mismatch/);
  assert.match(querySource, /withoutUnknownFilterValues/);
  assert.match(querySource, /postedAt:\s*\{\s*gte:/);
  assert.match(querySource, /buildSalaryRangeWhere\([\s\S]*filters\.salaryMin,[\s\S]*filters\.salaryMax,[\s\S]*filters\.salaryCurrency[\s\S]*Boolean\(filters\.includeUnknownSalary\)/);
  assert.match(querySource, /expandNormalizedRoleCategoryFilterValue\(filters\.roleCategory\)/);
  assert.match(querySource, /SALARY_COMPARISON_CURRENCIES/);
  assert.doesNotMatch(querySource, /salaryCurrency:\s*\{\s*notIn/);
  assert.match(querySource, /loadSalaryComparisonCurrency/);
  assert.match(querySource, /shouldUseJobFeedIndex\(filters: JobFilterParams, viewerProfileId: string \| null\)/);
  assert.match(querySource, /function hasScopedFeedRequest\(filters: JobFilterParams\)/);
  assert.match(querySource, /function hasNonDefaultJobStatusFilter\(value\?: string\)/);
  assert.match(querySource, /hasNonDefaultJobStatusFilter\(filters\.status\)/);
  assert.match(querySource, /const includeExactTotal = hasScopedFeedRequest\(filters\)/);
  assert.match(querySource, /getSelectiveScopedSearchIds/);
  assert.match(querySource, /structured filters, we still use[\s\S]*selective id list as a prefilter/);
  assert.match(querySource, /useDirectPrefilterSlice = canSlicePrefilterIds/);
  assert.match(querySource, /appendFeedIndexTextSearchWhere\(where, "company", filters\.companySearch\)/);
  assert.match(querySource, /appendFeedIndexTextSearchWhere\(where, "title", filters\.titleSearch\)/);
  assert.match(querySource, /appendFeedIndexLocationSearchWhere\(where, filters\.locationSearch\)/);
  assert.match(querySource, /canonicalJobIds = canonicalJobIds\.filter\(\(id\) => !passedJobIds\.has\(id\)\)/);
  assert.match(querySource, /buildNotAppliedCanonicalWhere/);
  assert.match(querySource, /if \(filters\.hideApplied && authUserId\)/);
  assert.match(querySource, /!filters\.hideApplied/);
  assert.match(querySource, /searchJobIds\(\s*filters\.search,\s*filters\.searchScope \?\? "all"/);
  assert.match(querySource, /buildSearchTermVariants/);
  assert.match(querySource, /const tsQuery = toTsQuery\(query\)/);
  assert.match(querySource, /\.join\("\\n        AND "\)/);
  assert.match(querySource, /repeated-character typo variants/);
  assert.match(querySource, /OR location ILIKE \$\{param\}/);
  assert.match(querySource, /type JobSortBy = "relevance" \| "newest" \| "deadline" \| "company"/);
  assert.match(querySource, /normalizeJobSortBy\(inputFilters\.sortBy\)/);
  assert.doesNotMatch(querySource, /filters\.sortBy === "salary"/);
  assert.doesNotMatch(querySource, /filters\.sortBy === "location"/);

  assert.match(pageSource, /buildActiveFilterGroups\(filters, resolvedSearchParams\)/);
  assert.match(pageSource, /formatJobResultCount/);
  assert.match(pageSource, /status: status === "LIVE" \? undefined : status/);
  assert.match(resultCountSource, /cached public-board count/);
  assert.match(pageSource, /buildLocationSearchRemoveHref/);
  assert.match(pageSource, /currentHadValues/);
  assert.match(pageSource, /return "\/jobs\?reset=1"/);
  assert.match(pageSource, /normalizeSearchParamsForHref\(params\)/);
  assert.match(pageSource, /if \(rawSearch && selectedSearchScope === "title"\)/);
  assert.match(pageSource, /else if \(rawSearch && selectedSearchScope === "all"\)/);
  assert.match(pageSource, /titleSearch = titleSearch \?\? rawSearch/);
  assert.match(pageSource, /splitFilterValues\(filters\.locationSearch\)/);
  assert.match(pageSource, /JobsActiveFilterChips/);
  assert.doesNotMatch(pageSource, /JobsNavigationPendingBoundary/);
  assert.match(pageSource, /PaginationControls/);
  assert.match(pageSource, /basePath="\/jobs"/);
  assert.match(paginationSource, /name="page"/);
  assert.match(paginationSource, /buildHiddenSearchInputs\(searchParams\)/);
  assert.doesNotMatch(paginationSource, /"use client"/);
  assert.match(pageSource, /getPageJumpError/);
  assert.match(paginationSource, /pageError\?: string \| null/);
  assert.doesNotMatch(paginationSource, /PageNumberLink/);
  assert.match(pendingBoundarySource, /Loading jobs/);
  assert.match(pendingBoundarySource, /autoapplication:jobs-loading-start/);
  assert.match(pendingBoundarySource, /showJobsLoadingPopup/);
  assert.match(pendingBoundarySource, /originHref/);
  assert.match(pendingBoundarySource, /pendingNavigation\?\.originHref === currentUrl/);
  assert.match(appShellSource, /<JobsNavigationPendingBoundary>/);
  assert.match(jobsLoadingSource, /<JobsLoadingPopup \/>/);
  assert.match(naturalLanguageSearchSource, /mergeNaturalLanguageJobsSearch\(searchParams, searchResult\.params\)/);
  assert.match(naturalLanguageSearchSource, /showJobsLoadingPopup\(href\)/);
  assert.match(loadingPopupSource, /fixed left-1\/2 top-5 z-50/);
  assert.match(loadingPopupSource, /-translate-x-1\/2/);
  assert.match(loadingPopupSource, /LoadingSpinner/);
  assert.match(loadingPopupSource, /Loading jobs/);
  assert.doesNotMatch(loadingPopupSource, /jobs-loading-sweep/);
  assert.doesNotMatch(loadingPopupSource, /bg-popover/);
  assert.doesNotMatch(loadingPopupSource, /shadow-\[/);
  assert.match(jobsLoadingSource, /surface-panel animate-pulse p-4 motion-reduce:animate-none sm:p-5/g);
  assert.doesNotMatch(jobsLoadingSource, /fixed inset-0/);
  assert.match(pendingBoundarySource, /onClickCapture/);
  assert.match(pendingBoundarySource, /onSubmitCapture/);
  assert.match(pendingBoundarySource, /buildGetFormHref/);
  assert.match(searchParamMemorySource, /inAppSearchParamMemory/);
  assert.match(searchParamMemorySource, /persistence\?: "memory" \| "local"/);
  assert.match(searchParamMemorySource, /window\.localStorage\.setItem\(storageKey, value\)/);
  assert.match(searchParamMemorySource, /window\.localStorage\.getItem\(storageKey\)/);
  assert.match(searchParamMemorySource, /firstRunForRouteInstance/);
  assert.match(searchParamMemorySource, /hasJobsStateParams\(searchParams\)/);
  assert.match(searchParamMemorySource, /if \(stateSearch\) \{[\s\S]*saveSearchParamMemory\(storageKey, stateSearch, persistence\);[\s\S]*return;/);
  assert.match(searchParamMemorySource, /clearInAppSearchParamMemory\(storageKey\)/);
  assert.doesNotMatch(searchParamMemorySource, /initializedMemoryKeys/);
  assert.doesNotMatch(searchParamMemorySource, /sessionStorage\.setItem\(storageKey/);
  assert.doesNotMatch(searchParamMemorySource, /sessionStorage\.getItem\(storageKey/);
  assert.match(pageSource, /persistence="local"/);
  assert.match(pageSource, /JOBS_SAVED_FILTER_PARAM_KEYS/);
  assert.match(pageSource, /JobsSavedFiltersControl/);
  assert.match(savedFiltersControlSource, /Saved/);
  assert.match(savedFiltersControlSource, /Clear saved filters/);
  assert.match(pendingBoundarySource, /closest\("details"\)\?\.removeAttribute\("open"\)/);
  assert.match(activeChipsSource, /Clear all/);
  assert.doesNotMatch(activeChipsSource, /setOptimisticState/);
  assert.doesNotMatch(activeChipsSource, /stateSignature/);
  assert.match(activeChipsSource, /hover:text-destructive/);
  assert.match(activeChipsSource, /focus-visible:ring-destructive\/30/);
  assert.doesNotMatch(activeChipsSource, /hover:bg-primary/);
  assert.match(pageSource, /name="salaryMax"/);
  assert.match(pageSource, /name="salaryCurrency"/);
  assert.match(pageSource, /name="includeUnknownSalary"/);
  assert.match(pageSource, /label="Hide applied jobs"/);
  assert.match(pageSource, /hideApplied: normalizeBooleanParam/);
  assert.match(pageSource, /SALARY_COMPARISON_CURRENCIES\.map/);
  assert.match(pageSource, /\{ label: "Recommended", value: undefined \}/);
  assert.match(pageSource, /\{ label: "Expiring soon", value: "deadline" \}/);
  assert.match(pageSource, /\{ label: "Company A-Z", value: "company" \}/);
  assert.doesNotMatch(pageSource, /\{ label: "Salary", value: "salary" \}/);
  assert.doesNotMatch(pageSource, /\{ label: "Location", value: "location" \}/);
  assert.match(pageSource, /getSearchParam\(searchParams, "sortBy"\) \?\? getSearchParam\(searchParams, "sort"\)/);
  assert.match(pageSource, /href=\{buildJobsHref\(resolvedSearchParams,[\s\S]*sortBy: option\.value/);
  assert.match(pageSource, /<FilterToggleField[\s\S]*name="expiry"[\s\S]*value="soon"/);
  assert.match(pageSource, /className="sm:col-span-2"[\s\S]*name="careerStage"/);
  assert.match(pageSource, /name="jobFunction"/);
  assert.match(pageSource, /title="Job function"/);
  assert.match(pageSource, /Job Function/);
  assert.match(pageSource, /name="industry"/);
  assert.match(pageSource, /Jobs must match all active filter sections/);
  assert.match(filterFieldSource, /"use client"/);
  assert.match(filterFieldSource, /setSelectedValues/);
  assert.match(filterFieldSource, /selectedLabels\.length/);
  assert.doesNotMatch(pageSource, /title="Deadline"/);
  assert.match(searchFormSource, /name: "searchScope"/);
  assert.match(searchFormSource, /filterFormId\?: string/);
  assert.match(searchFormSource, /form=\{filterFormId\}/);
  assert.match(searchFormSource, /action="\/jobs"/);
  assert.match(pageSource, /const JOBS_FILTER_FORM_ID = "jobs-filter-form"/);
  assert.match(pageSource, /filterFormId=\{JOBS_FILTER_FORM_ID\}/);
  assert.match(pageSource, /id=\{JOBS_FILTER_FORM_ID\}/);
  assert.match(pageSource, /action="\/jobs"/);
  assert.match(searchFormSource, /const SEARCH_SCOPE_OPTIONS/);
  assert.doesNotMatch(searchFormSource, /\{ label: "All", value: "all" \}/);
  assert.match(searchFormSource, /submittedSearchValue/);
  assert.match(searchFormSource, /titleSearch/);
  assert.match(searchFormSource, /companySearch/);
  assert.match(searchFormSource, /locationSearch/);
  assert.match(pageSource, /name="employmentType"/);
  assert.match(pageSource, /NORMALIZED_EMPLOYMENT_TYPE_GROUP_OPTIONS/);
  assert.match(metadataSource, /Internship \/ Co-op/);
  assert.match(pageSource, /name="posted"/);
  assert.doesNotMatch(pageSource, /name="source"/);
  assert.doesNotMatch(pageSource, /name="status"/);
  assert.doesNotMatch(pageSource, /const REGION_OPTIONS/);
});
